# This workflows will build and publish the python package when project is tagged in the v*.*.* form.
# For more information see:
# https://github.com/marketplace/actions/publish-python-poetry-package

name: CD
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v1.16
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          plugins: "poetry-dynamic-versioning[plugin]"
